apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: recipe-herissondev-certificate
  namespace: herissondev
spec:
  # certificats wildcard
  dnsNames:
  - 'recipe.herisson.dev'

  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-herissondev 
  secretName: recipe-herissondev-wildcard-certificate-secret
