apiVersion: apps/v1
kind: Deployment
metadata:
    name: receipe-herisson-dev
    namespace: herissondev
    labels:
        app: receipe-herisson-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: receipe-herisson-dev
    template:
        metadata:
            labels:
                app: receipe-herisson-dev
        spec:
            containers:
                - name: receipe-herisson-dev
                  image: aimerisson/receipe.herisson.dev:latest
                  ports:
                      - containerPort: 4000

                  env:
                      -   name: OPEN_AI_API_KEY
                          valueFrom:
                              secretKeyRef:
                                  name: receipe-herissondev-secret
                                  key: OPEN_AI_API_KEY
                      -   name: PHX_HOST
                          # env is herisson.dev
                          value: receipe.herisson.dev

                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: '500m'

