apiVersion: apps/v1
kind: Deployment
metadata:
    name: recipe-herisson-dev
    namespace: herissondev
    labels:
        app: recipe-herisson-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: recipe-herisson-dev
    template:
        metadata:
            labels:
                app: recipe-herisson-dev
        spec:
            containers:
                - name: recipe-herisson-dev
                  image: aimerisson/recipe.herisson.dev:latest
                  ports:
                      - containerPort: 4000

                  env:
                      - name: SECRET_KEY_BASE
                        valueFrom:
                            secretKeyRef:
                                name: recipe-herissondev-secret
                                key: SECRET_KEY_BASE
                      -   name: OPEN_AI_API_KEY
                          valueFrom:
                              secretKeyRef:
                                  name: recipe-herissondev-secret
                                  key: OPEN_AI_API_KEY
                      -   name: PHX_HOST
                          # env is herisson.dev
                          value: recipe.herisson.dev

                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: '500m'

