apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: herissondev-ingress-https
  namespace: herissondev
spec:
  entryPoints:
    websecure:
        address: ":443"
    web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https

  routes:
    - match: Host(`herisson.dev`)
      kind: Rule
      middlewares:
        - name: redirect-to-nonwww
          namespace: herissondev
      services:
        - name: herissondev-svc
          port: 4000
  tls:
    secretName: herissondev-wildcard-certificate-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-nonwww
  namespace: herissondev
spec:
  redirectRegex:
    permanent: true
    regex: ^(?:https://)?(?:www\.)?(.+)
    replacement: https://${1}
