apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: recipe-herissondev-ingress-https
  namespace: herissondev
spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`recipe.herisson.dev`)
      kind: Rule
      middlewares:
        - name: redirect-to-nonwww
          namespace: herissondev
      services:
        - name: recipe-herissondev-svc
          port: 4000
  tls:
    secretName: recipe-herissondev-wildcard-certificate-secret

