apiVersion: v1
kind: Service
metadata:
    name: receipe-herissondev-svc
    namespace: herissondev
spec:
    type: ClusterIP
    selector:
        app: receipe-herisson-dev
    ports:
        - protocol: 'TCP'
          port: 4000
          targetPort: 4000
